name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy website
        run: |
          rsync -av --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            ./ /var/www/mikebernal.me/